name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    strategy:
      matrix:
        python-version: ['3.6', '3.7', '3.8', '3.9', '3.10', '3.11', '3.12', '3.13']
    
    runs-on: ubuntu-latest
    container: ${{ matrix.python-version == '3.6' && 'python:3.6' || matrix.python-version == '3.7' && 'python:3.7' || null }}

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python ${{ matrix.python-version }}
      if: ${{ matrix.python-version != '3.6' && matrix.python-version != '3.7' }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e ".[dev]"
    
    - name: Lint with flake8
      run: |
        flake8 refib tests
    
    - name: Check formatting with black
      run: |
        black --check refib tests
    
    - name: Test with pytest
      run: |
        pytest --cov=refib --cov-report=term-missing --cov-fail-under=100
    
    - name: Type check with mypy
      if: matrix.python-version != '3.6'  # mypy has issues with 3.6
      run: |
        mypy refib